### ISSUE TITLE
Extension is broken for no reason.

### ISSUE THREAD

**Issue by lKomus** [joaopsys/NowStreaming-Firefox#2]
NowStreaming was working well yesterday, but now it seems to be stuck reporting the same streamers I follow regardless if they're streaming or not, the uptime periods are ridiculous. Here's a screenshot comparing how it is on Twitch and what the extension shows.

![firefox_TlDg8l31NN](https://github.com/joaopsys/NowStreaming-Firefox/assets/4800879/0c35fd62-a1c4-4fe5-aefb-ad04f5dc1706)

I'm using Firefox 117.0. I've tried reinstalling the extension and installing it again, re-authenticating, deleting and adding again my streamers list, and it didn't work.

**Comment by joaopsys** [comment]
Hi @lKomus thank you for reporting this. I can't reproduce this problem on FF 117 as well and I haven't heard any other reports.

Is the issue still happening for you or has it self-healed?

**Comment by lKomus** [comment]
Hello, I reinstalled the extension and the issue is not present anymore. Will see if the issue appears again but it's such a weird one I think it's unlikely it will. Closing the issue.
